language: c
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository ppa:chris-lea/redis-server -y
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake libglib2.0-dev libgee-0.8
         valac-0.30 gobject-introspection libgirepository1.0-dev redis
  - sudo /etc/init.d/redis restart

before_script:
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/h/hiredis/libhiredis-dev_0.13.3-2_amd64.deb
  - wget http://mirrors.kernel.org/ubuntu/pool/universe/h/hiredis/libhiredis0.13_0.13.3-2_amd64.deb
  - sudo dpkg -i libhiredis-dev_0.13.3-2_amd64.deb libhiredis0.13_0.13.3-2_amd64.deb
  - mkdir build
  - cd build

script: cmake .. && make && cd test && gtester --verbose ./test-gredis
